//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.06 at 09:50:27 AM EEST 
//


package adstream.yadn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:adstream:yadn}MessageID"/>
 *         &lt;element ref="{urn:adstream:yadn}Status"/>
 *         &lt;element ref="{urn:adstream:yadn}FileID"/>
 *         &lt;element ref="{urn:adstream:yadn}FileName"/>
 *         &lt;element ref="{urn:adstream:yadn}FileDirectory"/>
 *         &lt;element ref="{urn:adstream:yadn}FileSize"/>
 *         &lt;element ref="{urn:adstream:yadn}MD5"/>
 *         &lt;element ref="{urn:adstream:yadn}CRC"/>
 *         &lt;element ref="{urn:adstream:yadn}Node"/>
 *         &lt;element ref="{urn:adstream:yadn}SpecDBDocID"/>
 *         &lt;element ref="{urn:adstream:yadn}metadata"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageID",
    "status",
    "fileID",
    "fileName",
    "fileDirectory",
    "fileSize",
    "md5",
    "crc",
    "node",
    "specDBDocID",
    "metadata"
})
@XmlRootElement(name = "UploadJobResponse")
public class UploadJobResponse {

    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "FileID", required = true)
    protected String fileID;
    @XmlElement(name = "FileName", required = true)
    protected String fileName;
    @XmlElement(name = "FileDirectory", required = true)
    protected String fileDirectory;
    @XmlElement(name = "FileSize", required = true)
    protected String fileSize;
    @XmlElement(name = "MD5", required = true)
    protected String md5;
    @XmlElement(name = "CRC", required = true)
    protected String crc;
    @XmlElement(name = "Node", required = true)
    protected String node;
    @XmlElement(name = "SpecDBDocID", required = true)
    protected String specDBDocID;
    @XmlElement(required = true)
    protected Metadata metadata;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the fileID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileID() {
        return fileID;
    }

    /**
     * Sets the value of the fileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileID(String value) {
        this.fileID = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the fileDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDirectory() {
        return fileDirectory;
    }

    /**
     * Sets the value of the fileDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDirectory(String value) {
        this.fileDirectory = value;
    }

    /**
     * Gets the value of the fileSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * Sets the value of the fileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSize(String value) {
        this.fileSize = value;
    }

    /**
     * Gets the value of the md5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMD5() {
        return md5;
    }

    /**
     * Sets the value of the md5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMD5(String value) {
        this.md5 = value;
    }

    /**
     * Gets the value of the crc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRC() {
        return crc;
    }

    /**
     * Sets the value of the crc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRC(String value) {
        this.crc = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode(String value) {
        this.node = value;
    }

    /**
     * Gets the value of the specDBDocID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecDBDocID() {
        return specDBDocID;
    }

    /**
     * Sets the value of the specDBDocID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecDBDocID(String value) {
        this.specDBDocID = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
